### ISSUE TITLE
Cannot run both rails server and guard together

### ISSUE THREAD

**Issue by ronyv89** [guard/notiffany#24]
Running both `guard` and `rails server` together, forces atleast 1 of them to quit because of `notiffany`

Stack trace for guard

```
/Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/notiffany-0.1.0/lib/notiffany/notifier.rb:194:in `_activate': Already connected (RuntimeError)
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/notiffany-0.1.0/lib/notiffany/notifier.rb:87:in `initialize'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/notiffany-0.1.0/lib/notiffany/notifier.rb:42:in `new'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/notiffany-0.1.0/lib/notiffany/notifier.rb:42:in `connect'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/guard-2.14.0/lib/guard/notifier.rb:11:in `connect'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/guard-2.14.0/lib/guard.rb:61:in `setup'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/guard-2.14.0/lib/guard/commander.rb:32:in `start'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/guard-2.14.0/lib/guard/cli/environments/valid.rb:16:in `start_guard'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/guard-2.14.0/lib/guard/cli.rb:122:in `start'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/guard-2.14.0/lib/guard/aruba_adapter.rb:32:in `execute'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/guard-2.14.0/lib/guard/aruba_adapter.rb:19:in `execute!'
	from /Users/ronyvarghese/.rvm/gems/ruby-2.3.1@stack_track/gems/guard-2.14.0/bin/_guard-core:11:in `<main>'
``` 

Note: Works for `webrick` rails server. Fails for `Puma`

**Comment by e2** [comment]
I'd be happy to fix this.

Can you create a minimal example where this fails? (It would help me fix this quickly and release as soon as I do).

**Comment by mattscilipoti** [comment]
This same issue just started for me.  It was caused by a duplicate entry in the Guardfile for `guard :teaspoon...`.  I figured this may help others with a similar mistake.

**Comment by e2** [comment]
Can someone create a small repo to reproduce this?

(That way I can work out where both connections are happening and which one should be used, etc).

**Comment by ianfleeton** [comment]
Hi, I've stumbled across this, also with puma and teaspoon. I've put together a minimal repo as suggested at https://github.com/ianfleeton/notiffany-issue-24

Steps to reproduce (each a commit in the above repo):

* rails new notiffany-issue-24 --skip-test-unit
* Add guard-rspec to Gemfile
* bundle exec guard init rspec
* Add guard-teaspoon to Gemfile, in :development, :test
* Add gem teaspoon-jasmine to :development, :test
* rails generate teaspoon:install
* bundle exec guard init teaspoon
* Add gem phantomjs to Gemfile, in :test

Run either `rails s` or `bundle exec guard` one after another; either will quit the other running before it.

**Comment by ianfleeton** [comment]
@e2 not sure if you'd seen my comment with the repro repo? Cheers!
