### ISSUE TITLE
tmux/client.rb:12:in `Float': can't convert nil into Float (TypeError)

### ISSUE THREAD

**Issue by zx1986** [guard/notiffany#29]
Run in on macOS.

Ruby: 2.3.1
Guard: 2.14.1

```
guard start                                                                                                                                     

Warning: you have a Gemfile, but you're not using bundler or RUBYGEMS_GEMDEPS
01:04:14 - INFO - Guard here! It looks like your project has a Gemfile, yet you are running
> [#] `guard` outside of Bundler. If this is your intent, feel free to ignore this
> [#] message. Otherwise, consider using `bundle exec guard` to ensure your
> [#] dependencies are loaded correctly.
> [#] (You can run `guard` with --no-bundler-warning to get rid of this message.)

/Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/tmux/client.rb:12:in `Float': can't convert nil into Float (TypeError)

        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/tmux/client.rb:12:in `version'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/tmux.rb:69:in `_check_available'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/base.rb:59:in `initialize'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/detected.rb:100:in `new'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/detected.rb:100:in `_add'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/detected.rb:62:in `block (2 levels) in detect'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/detected.rb:60:in `each'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/detected.rb:60:in `detect'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/detected.rb:60:in `block in detect'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/detected.rb:59:in `each'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier/detected.rb:59:in `detect'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier.rb:180:in `_detect_or_add_notifiers'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier.rb:198:in `_activate'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier.rb:87:in `initialize'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier.rb:42:in `new'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/notiffany-0.1.1/lib/notiffany/notifier.rb:42:in `connect'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-2.14.1/lib/guard/notifier.rb:11:in `connect'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-2.14.1/lib/guard.rb:61:in `setup'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-2.14.1/lib/guard/commander.rb:32:in `start'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-2.14.1/lib/guard/cli/environments/valid.rb:16:in `start_guard'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-2.14.1/lib/guard/cli.rb:122:in `start'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-2.14.1/lib/guard/aruba_adapter.rb:32:in `execute'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-2.14.1/lib/guard/aruba_adapter.rb:19:in `execute!'
        from /Users/zx1986/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/guard-2.14.1/bin/_guard-core:11:in `<main>'
```

**Comment by zx1986** [comment]
`tmux -V` had return `tmux master`
